server:
  port: 9090
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/felipeDurante/repositorio-config-files

#  profiles:
#    active: native

